{"name": "test_login_1_user_wrongFormat[data1]", "status": "failed", "statusDetails": {"message": "AssertionError: assert '账号不能为空' == '用户名不能为空'\n  - 账号不能为空\n  + 用户名不能为空", "trace": "self = <TestCases.test_loginpage_pytest.TestLogin object at 0x0000000003DA26C8>, data = {'check': '用户名不能为空', 'passwd': '123456', 'user': ''}\n\n    @pytest.mark.parametrize('data',LD.userwrongdate)\n    def test_login_1_user_wrongFormat(self,data):\n        my_logger.info('此时输入的用户名是{0}密码是{1}'.format(data['user'],data['passwd']))\n        #步骤  输入用户名 密码点击登录\n        self.lg.login(data['user'],data['passwd'])\n        #断言，登录页面提示\n        #登录页面中，获取登录框中文本内容\n        #对比文本内容与期望值是否相等\n>       assert LoginPage(self.driver).user_errMsg()==data['check']\nE       AssertionError: assert '账号不能为空' == '用户名不能为空'\nE         - 账号不能为空\nE         + 用户名不能为空\n\ntest_loginpage_pytest.py:64: AssertionError"}, "attachments": [{"name": "log", "source": "0ed51c16-a9eb-44a7-a23b-a6c497525492-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '', 'passwd': '123456', 'check': '用户名不能为空'}"}], "start": 1587110023300, "stop": 1587110025702, "uuid": "e6ee9714-d162-463b-b3b0-a4f85f23253b", "historyId": "7f147379897caa3ececbc1acfcf79e1b", "testCaseId": "a2b30b9fcbe62a70505f513107d4524a", "fullName": "TestCases.test_loginpage_pytest.TestLogin#test_login_1_user_wrongFormat", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_loginpage_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "HAOXUEJUN"}, {"name": "thread", "value": "9988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_loginpage_pytest"}]}